print('Hello World!!')
print("===================================")
print('Python programming is very easy')
print('How are you')
print('I am fine, thank you and you?')
print("===================================")
